version: '3.8'

services:
  postgres:
    image: 'postgres:15.4-alpine3.18'
    container_name: local-postgres-doghub
    restart: always
    environment:
      - POSTGRES_USER=doghub
      - POSTGRES_PASSWORD=doghub_password
    ports:
      - "54322:5432"
    volumes:
      - postgres:/var/lib/postgresql/data1
volumes:
  postgres:
    driver: local